### ISSUE TITLE
License / Status

### ISSUE THREAD

**Issue by teameh** [clayellis/APReorderableStackView#5]
Hi Clay,

Great work on this demo project! It works like a charm. 🎉 

Can this code be used by other parties? Could you add a [license](https://choosealicense.com/) to the repo? I can submit a PR if you don't have time for this. 

Also, do you plan on maintaining this code? It would be cool to create a CocoaPod for this. I could also fork it an go ahead if you have no plans and wouldn't mind.

Cheers,
Tieme

**Comment by clayellis** [comment]
@teameh feel free to open PRs for the license and the pod! I don't have much time to go back and look at this at the moment, but I'll respond to comments and PRs!

**Comment by teameh** [comment]
Great! I've added 3 PR's

**Comment by clayellis** [comment]
Thanks for making those!

**Comment by teameh** [comment]
Thanks for your quick response! 

What is your current view on the code and style of the project. Shall I add a PR to cleanup some stuff? If so could you let me know what you want? 

- remove explicit `selfs` 
- remove duplicate code
- Add missing  `didReorder` delegate method (the comment in the protocol is there, implementation is not)

Lastly, the pod needs to be added to cocoapods. See https://guides.cocoapods.org/making/getting-setup-with-trunk.html I could also do this if you add me as a contributor

**Comment by clayellis** [comment]
@teameh the project definitely needs some cleaning up. I'd actually like to take some time to update it (it's been a few years since I've touched this.) Once I'm done with that and lay a new baseline, I'll get to the other steps.

**Comment by teameh** [comment]
Allright 😀

**Comment by teameh** [comment]
Please let me know if I can do anything to help you with this @clayellis. Cheers!
